git-type: cmd
branch: replace-autofix-ci-action-2
skip-forks: true
# org:
#   - lintnet # Update with your organization
#   - lintnet-modules
#   - aquaproj
# user:
#   - suzuki-shunsuke
# repo:
#   - lintnet-modules/ghalint # For test
labels:
  - replace-autofix-ci-action-2
pr-title: "ci: Replace suzuki-shunsuke/autofix-ci-action with autofix-ci/action"
pr-body: |
  - https://github.com/suzuki-shunsuke/batch-task/issues/13
# code-search: filename:.github/workflows/autofix.yaml org:lintnet-modules
code-search: filename:.github/workflows/autofix.yaml org:csm-actions org:aquaproj org:lintnet-modules org:lintnet user:suzuki-shunsuke
# code-search: filename:.github/workflows/autofix.yaml user:suzuki-shunsuke
